### ISSUE TITLE
Deploying manifest 1.0.2 on top of 1.0.1 creates a lot of errors with patch

### ISSUE THREAD

**Issue by apryiomka** [kubeflow/manifests#1127] opened 2020-04-21 18:35 UTC
When applying v1.0.2 manifest on previously deployed v.1.0.1 I see a lot of deployments patching fail like so:
```
time="2020-04-21T18:19:02Z" level=warning msg="Encountered error applying application scheduledworkflow:  (kubeflow.error): Code 500 with message: Apply.Run  Error error when applying patch

{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"ml-pipeline-scheduledworkflow","app.kubernetes.io/component":"scheduledworkflow","app.kubernetes.io/instance":"scheduledworkflow-0.2.5","app.kubernetes.io/managed-by":"kfctl","app.kubernetes.io/name":"scheduledworkflow","app.kubernetes.io/part-of":"kubeflow","app.kubernetes.io/version":"0.2.5"},"name":"ml-pipeline-scheduledworkflow","namespace":"kubeflow"},"spec":{"selector":{"matchLabels":{"app":"ml-pipeline-scheduledworkflow","app.kubernetes.io/component":"scheduledworkflow","app.kubernetes.io/instance":"scheduledworkflow-0.2.5","app.kubernetes.io/managed-by":"kfctl","app.kubernetes.io/name":"scheduledworkflow","app.kubernetes.io/part-of":"kubeflow","app.kubernetes.io/version":"0.2.5"}},"template":{"metadata":{"labels":{"app":"ml-pipeline-scheduledworkflow","app.kubernetes.io/component":"scheduledworkflow","app.kubernetes.io/instance":"scheduledworkflow-0.2.5","app.kubernetes.io/managed-by":"kfctl","app.kubernetes.io/name":"scheduledworkflow","app.kubernetes.io/part-of":"kubeflow","app.kubernetes.io/version":"0.2.5"}},"spec":{"containers":[{"env":[{"name":"POD_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}}],"image":"gcr.io/ml-pipeline/scheduledworkflow:0.2.5","imagePullPolicy":"IfNotPresent","name":"ml-pipeline-scheduledworkflow"}],"serviceAccountName":"ml-pipeline-scheduledworkflow"}}}}"},"labels":{"app.kubernetes.io/instance":"scheduledworkflow-0.2.5","app.kubernetes.io/version":"0.2.5"}},"spec":{"selector":{"matchLabels":{"app.kubernetes.io/instance":"scheduledworkflow-0.2.5","app.kubernetes.io/version":"0.2.5"}},"template":{"metadata":{"labels":{"app.kubernetes.io/instance":"scheduledworkflow-0.2.5","app.kubernetes.io/version":"0.2.5"}},"spec":{"$setElementOrder/containers":[{"name":"ml-pipeline-scheduledworkflow"}],"containers":[{"image":"gcr.io/ml-pipeline/scheduledworkflow:0.2.5","name":"ml-pipeline-scheduledworkflow"}]}}}}
to:Resource: "apps/v1, Resource=deployments", GroupVersionKind: "apps/v1, Kind=Deployment"Name: "ml-pipeline-scheduledworkflow", Namespace: "kubeflow"Object: {map["apiVersion":"apps/v1" "kind":"Deployment" "metadata":map["annotations":map["deployment.kubernetes.io/revision":"1" "kubectl.kubernetes.io/last-applied-configuration":"{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"ml-pipeline-scheduledworkflow","app.kubernetes.io/component":"scheduledworkflow","app.kubernetes.io/instance":"scheduledworkflow-0.2.0","app.kubernetes.io/managed-by":"kfctl","app.kubernetes.io/name":"scheduledworkflow","app.kubernetes.io/part-of":"kubeflow","app.kubernetes.io/version":"0.2.0"},"name":"ml-pipeline-scheduledworkflow","namespace":"kubeflow"},"spec":{"selector":{"matchLabels":{"app":"ml-pipeline-scheduledworkflow","app.kubernetes.io/component":"scheduledworkflow","app.kubernetes.io/instance":"scheduledworkflow-0.2.0","app.kubernetes.io/managed-by":"kfctl","app.kubernetes.io/name":"scheduledworkflow","app.kubernetes.io/part-of":"kubeflow","app.kubernetes.io/version":"0.2.0"}},"template":{"metadata":{"labels":{"app":"ml-pipeline-scheduledworkflow","app.kubernetes.io/component":"scheduledworkflow","app.kubernetes.io/instance":"scheduledworkflow-0.2.0","app.kubernetes.io/managed-by":"kfctl","app.kubernetes.io/name":"scheduledworkflow","app.kubernetes.io/part-of":"kubeflow","app.kubernetes.io/version":"0.2.0"}},"spec":{"containers":[{"env":[{"name":"POD_NAMESPACE","valueFrom":{"fieldRef":{"fieldPath":"metadata.namespace"}}}],"image":"gcr.io/ml-pipeline/scheduledworkflow:0.2.0","imagePullPolicy":"IfNotPresent","name":"ml-pipeline-scheduledworkflow"}],"serviceAccountName":"ml-pipeline-scheduledworkflow"}}}}"] "creationTimestamp":"2020-03-12T19:56:43Z" "generation":'x01' "labels":map["app":"ml-pipeline-scheduledworkflow" "app.kubernetes.io/component":"scheduledworkflow" "app.kubernetes.io/instance":"scheduledworkflow-0.2.0" "app.kubernetes.io/managed-by":"kfctl" "app.kubernetes.io/name":"scheduledworkflow" "app.kubernetes.io/part-of":"kubeflow" "app.kubernetes.io/version":"0.2.0"] "name":"ml-pipeline-scheduledworkflow" "namespace":"kubeflow" "ownerReferences":[map["apiVersion":"app.k8s.io/v1beta1" "blockOwnerDeletion":%!q(bool=true) "controller":%!q(bool=false) "kind":"Application" "name":"scheduledworkflow" "uid":"98928e05-649b-11ea-b201-0671d77f8e88"]] "resourceVersion":"29797512" "selfLink":"/apis/apps/v1/namespaces/kubeflow/deployments/ml-pipeline-scheduledworkflow" "uid":"988f6d6f-649b-11ea-b201-0671d77f8e88"] "spec":map["progressDeadlineSeconds":'u0258' "replicas":'x01' "revisionHistoryLimit":'' "selector":map["matchLabels":map["app":"ml-pipeline-scheduledworkflow" "app.kubernetes.io/component":"scheduledworkflow" "app.kubernetes.io/instance":"scheduledworkflow-0.2.0" "app.kubernetes.io/managed-by":"kfctl" "app.kubernetes.io/name":"scheduledworkflow" "app.kubernetes.io/part-of":"kubeflow" "app.kubernetes.io/version":"0.2.0"]] "strategy":map["rollingUpdate":map["maxSurge":"25%" "maxUnavailable":"25%"] "type":"RollingUpdate"] "template":map["metadata":map["creationTimestamp":<nil> "labels":map["app":"ml-pipeline-scheduledworkflow" "app.kubernetes.io/component":"scheduledworkflow" "app.kubernetes.io/instance":"scheduledworkflow-0.2.0" "app.kubernetes.io/managed-by":"kfctl" "app.kubernetes.io/name":"scheduledworkflow" "app.kubernetes.io/part-of":"kubeflow" "app.kubernetes.io/version":"0.2.0"]] "spec":map["containers":[map["env":[map["name":"POD_NAMESPACE" "valueFrom":map["fieldRef":map["apiVersion":"v1" "fieldPath":"metadata.namespace"]]]] "image":"gcr.io/ml-pipeline/scheduledworkflow:0.2.0" "imagePullPolicy":"IfNotPresent" "name":"ml-pipeline-scheduledworkflow" "resources":map[] "terminationMessagePath":"/dev/termination-log" "terminationMessagePolicy":"File"]] "dnsPolicy":"ClusterFirst" "restartPolicy":"Always" "schedulerName":"default-scheduler" "securityContext":map[] "serviceAccount":"ml-pipeline-scheduledworkflow" "serviceAccountName":"ml-pipeline-scheduledworkflow" "terminationGracePeriodSeconds":'x1e']]] "status":map["availableReplicas":'x01' "conditions":[map["lastTransitionTime":"2020-03-12T19:56:44Z" "lastUpdateTime":"2020-03-12T19:57:25Z" "message":"ReplicaSet "ml-pipeline-scheduledworkflow-6c978b6b85" has successfully progressed." "reason":"NewReplicaSetAvailable" "status":"True" "type":"Progressing"] map["lastTransitionTime":"2020-04-21T17:36:11Z" "lastUpdateTime":"2020-04-21T17:36:11Z" "message":"Deployment has minimum availability." "reason":"MinimumReplicasAvailable" "status":"True" "type":"Available"]] "observedGeneration":'x01' "readyReplicas":'x01' "replicas":'x01' "updatedReplicas":'x01']]}
for: "/tmp/kout361420906": Deployment.apps "ml-pipeline-scheduledworkflow" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string 
{"app":"ml-pipeline-scheduledworkflow", "app.kubernetes.io/component":"scheduledworkflow", "app.kubernetes.io/instance":"scheduledworkflow-0.2.5", "app.kubernetes.io/managed-by":"kfctl", "app.kubernetes.io/name":"scheduledworkflow", "app.kubernetes.io/part-of":"kubeflow", "app.kubernetes.io/version":"0.2.5"}

MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable" filename="kustomize/kustomize.go:202"
```

**Comment by jlewi** [comment] 2020-04-22 20:55
Duplicate of #1131

**Closed by jlewi** 2020-04-22 20:55 UTC
Labels: kind/bug
