### ISSUE TITLE
K8s 1.25 and Manifests WG

### ISSUE THREAD

**Issue by kimwnasptd** [kubeflow/manifests#2325] opened 2022-11-22 09:13 UTC
Tracking issue for all updates that we have to do in the common components of manifests to work with K8s 1.25. With a quick look we took with @apo-ger the biggest item is the deprecation of the `policy/v1beta1` API version, and the object that affects most of the components is `PodDisruptionBudget`

This is a draft plan of the common components and the target versions:
| Status | Component | Proposed Version | Context/PRs |
| --- | --- | ---| --- |
| ✅ | Istio | v1.16 | https://github.com/kubeflow/manifests/pull/2327 |
| ✅  | Knative | v1.8 | https://github.com/kubeflow/manifests/issues/2325#issuecomment-1325718698 https://github.com/knative/community/blob/main/mechanics/RELEASE-SCHEDULE.md#upcoming-releases|
| ✅ | Cert Manager | v1.10 | https://github.com/kubeflow/manifests/pull/2330 |

I'll also update the issue further with other changes we'll need to do for K8s 1.25

cc @kubeflow/wg-manifests-leads

**Comment by apo-ger** [comment] 2022-11-22 16:06
We noticed that the generated manifests of `Istio v1.6.0` include some `policy/v1` `PodDisruptionBudget` resources that we need to remove. (see https://github.com/istio/istio/issues/12602 and https://github.com/istio/istio/issues/24000)

Until now we have used two patches to address this:
- [common/istio-1-16/istio-install/base/patches/remove-pdb.yaml](https://github.com/kubeflow/manifests/blob/master/common/istio-1-14/istio-install/base/patches/remove-pdb.yaml)
- [common/istio-1-16/cluster-local-gateway/base/patches/remove-pdb.yaml](https://github.com/kubeflow/manifests/blob/master/common/istio-1-14/cluster-local-gateway/base/patches/remove-pdb.yaml)
    
However these patches do not work with kustomize `v3.2.0`. The problem is that `v3.2.0` doesn't have the appropriate openapi schema for the `policy/v1` API version resources:
- https://github.com/kubernetes-sigs/kustomize/issues/4495

This is fixed in `kustomize v4+`:
- https://github.com/kubernetes-sigs/kustomize/issues/3694#issuecomment-799700607
    
I opened a PR with the following proposed changes: 
- Disable the delete patches until we upgrade to `kustomize v4+`.
  - tracked in: https://github.com/kubeflow/manifests/issues/1797
 - As a temporary workaraound we remove PodDisruptionBudget resources
      manually with yq before deploying Istio manifests.
 - Update README file with instructions.

**Comment by kimwnasptd** [comment] 2022-11-23 15:30
@yuzisun which Knative version should we target for the KF 1.7 release? 

Our target K8s version is 1.25, so we'll need a Knative version that works both with that K8s version as well as the KServe version we'll include in KF 1.7

**Comment by yuzisun** [comment] 2022-11-23 22:14
> @yuzisun which Knative version should we target for the KF 1.7 release?
> 
> Our target K8s version is 1.25, so we'll need a Knative version that works both with that K8s version as well as the KServe version we'll include in KF 1.7

@kimwnasptd Let's target to Knative 1.8 though there is [an issue](https://github.com/knative/serving/issues/13487) I opened which affects KServe and we will need a patched release after Knative fixes the issue.

**Comment by apo-ger** [comment] 2022-11-24 10:31
I've sent a [PR](https://github.com/kubeflow/manifests/pull/2330) to upgrade cert-manager to latest version (v1.10.1)

**Comment by apo-ger** [comment] 2022-11-25 16:19
Here is the [PR](https://github.com/kubeflow/manifests/pull/2333) for upgrading `knative-eventing` to `v1.8.1`

**Closed** 2023-01-24 16:02 UTC
