### ISSUE TITLE
Registration flow is missing in v1.1.0

### ISSUE THREAD

**Issue by subodh101** [kubeflow/manifests#1496] opened 2020-08-18 04:00 UTC
What?
Registration flow feature is missing in the [tag v1.1.0](https://github.com/kubeflow/manifests/blob/v1.1.0/common/centraldashboard/base/params.env)
This feature is needed as per the [documentation](https://www.kubeflow.org/docs/components/multi-tenancy/getting-started/#automatic-creation-of-profiles)

**Comment by subodh101** [comment] 2020-08-18 04:54
Using [master](https://github.com/kubeflow/gcp-blueprints/blob/master/kubeflow/Makefile#L29) fixes the issue.

**Comment by subodh101** [comment] 2020-08-18 05:55
The instance is supposed to fetch from [1.1 branch](https://www.kubeflow.org/docs/gke/deploy/deploy-cli/#fetch-packages-using-kpt). A little explanation would be appreciated. 🙇

**Comment by 814HiManny** [comment] 2020-09-06 02:22
I have encountered the same issue. In my case I have followed the [kfctl_istio_dex.v1.1.0.yaml](https://raw.githubusercontent.com/kubeflow/manifests/v1.1-branch/kfdef/kfctl_istio_dex.v1.1.0.yaml) installation instructions. This configuration references:
```
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: stacks/kubernetes
    name: kubeflow-apps
```

which references `https://github.com/kubeflow/manifests/blob/v1.1-branch/common/centraldashboard/base_v3/kustomization.yaml`

this kustomization.yaml is not updated to the latest gcr.io/kubeflow-images-public/centraldashboard tag. The newTag should be changed from `vmaster-gf39279c0` to `v1.1.0-g35d7484a`

I have also thus far noticed the same for `https://github.com/kubeflow/manifests/blob/v1.1-branch/profiles/base_v3/kustomization.yaml` where NewTag for `gcr.io/kubeflow-images-public/profile-controller` should be changed from `vmaster-g34aa47c2` to `v1.1.0-ga49f658f`

**Comment by thesuperzapper** [comment] 2020-09-15 01:55
For those following, it looks like the Kubeflow 1.1 release was botched quite badly (from a manifest perspective), I raised issue #1553

**Comment by jlewi** [comment] 2020-09-22 13:40
The Kubeflow release ships whatever application versions are available in the manifests. If the manifests aren't up to date then we ship an older version. It is application owners responsibility to ensure their changes make it into the KF release. 

/cc @lalithvaka

**Comment by subodh101** [comment] 2020-09-22 13:51
> Using master fixes the issue.

I updated the kubeflow with master version and set `registration-flow=true`. However, it didn't work. I can retry just incase that problem is fixed. It is a very important issue at the moment as we are running too many namespaces without any reason.

**Comment by subodh101** [comment] 2020-10-06 05:44
The problem was with the centraldashboard base version.
[This](https://github.com/kubeflow/manifests/blob/master/stacks/gcp/kustomization.yaml#L9) calls the stack gcp.
Which further calls the [base_v3](https://github.com/kubeflow/manifests/blob/c728bc737cfadc2816ecd50c5c96ee59cd1d9b1a/common/centraldashboard/overlays/stacks/kustomization.yaml#L10).
[base_v3](https://github.com/kubeflow/manifests/blob/master/common/centraldashboard/base_v3/kustomization.yaml) doesn't have the updated patch only base has that.

https://github.com/kubeflow/manifests/pull/1049#issue-393345605
This seems to be the reason for not using base.

One solution is to get rid of `vars` in the base centraldashboard but that will probably break the `kfctl` installation. I don't think we can make them optional in such a way to ignore `vars` if present in the "global" `vars`.
Another solution that I can think of is to update base_v3 but that will always need to be updated.

Let me know which is a better solution.
cc: @jlewi

**Comment by thesuperzapper** [comment] 2020-10-06 06:53
As a temporary workaround for Kubeflow 1.1, you can do what I mentioned at: https://github.com/kubeflow/manifests/issues/1553#issuecomment-695910339

**Comment by jlewi** [comment] 2020-10-08 13:05
Duplicate of kubeflow/kubeflow#4889

**Closed by jlewi** 2020-10-08 13:05 UTC
Labels: kind/feature, platform/gcp
