### ISSUE TITLE
What's the usage of tensorboard manifest?

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/manifests#1089] opened 2020-04-09 22:34 UTC
Seems manifest [tensorboard](https://github.com/kubeflow/manifests/tree/master/tensorboard) is just one tensorboard instance. 

logs points to the local directory. I don't know why we need this manifest and how to use it? 
https://github.com/kubeflow/manifests/blob/master/tensorboard/base/deployment.yaml#L18

Instead, I think `tensorboard-controller` could be added to manifest?  it helps to reduce efforts to create a tensorboard, controller manages deployment, service, virtual service already.  Examples like mnist (https://github.com/kubeflow/examples/blob/master/mnist/mnist_*.ipynb) can leverage this as well.

**Comment by Jeffwan** [comment] 2020-04-09 22:35
If user think this is reasonable. I will do some tests on `tensorboard-controller` and bring manifest here. 

Meanwhile, it's better to make sure if we use [tensorboard](https://github.com/kubeflow/manifests/tree/master/tensorboard) or not.

**Comment by jlewi** [comment] 2020-04-10 00:06
Duplicate of #415
We should remove the tensorboard manifest.

**Comment by jlewi** [comment] 2020-04-10 00:06
Duplicate of #415

**Closed by jlewi** 2020-04-10 00:06 UTC
