### ISSUE TITLE
document missing kustomize targets that need to be ported from ksonnet

### ISSUE THREAD

**Issue by kkasravi** [kubeflow/manifests#55] opened 2019-05-08 10:24 UTC
the list of ksonnet prototypes is

./application/prototypes/application.jsonnet
./argo/prototypes/argo.jsonnet
./automation/prototypes/release.jsonnet
./aws/prototypes/aws-alb-ingress-controller.jsonnet
./aws/prototypes/aws-efs-csi-driver.jsonnet
./aws/prototypes/aws-efs-pv.jsonnet
./aws/prototypes/aws-fsx-csi-driver.jsonnet
./aws/prototypes/aws-fsx-pv-dynamic.jsonnet
./aws/prototypes/aws-fsx-pv-static.jsonnet
./aws/prototypes/istio-ingress.jsonnet
./chainer-job/prototypes/chainer-job-simple.jsonnet
./chainer-job/prototypes/chainer-job.jsonnet
./chainer-job/prototypes/chainer-operator.jsonnet
./common/prototypes/ambassador.jsonnet
./common/prototypes/basic-auth.jsonnet
./common/prototypes/centraldashboard.jsonnet
./common/prototypes/echo-server.jsonnet
./common/prototypes/spartakus.jsonnet
./credentials-pod-preset/prototypes/gcp-credentials-pod-preset.jsonnet
./examples/prototypes/katib-studyjob-test-v1alpha1.jsonnet
./examples/prototypes/tensorboard.jsonnet
./examples/prototypes/tf-job-simple-v1beta1.jsonnet
./examples/prototypes/tf-job-simple-v1beta2.jsonnet
./examples/prototypes/tf-job-simple.jsonnet
./examples/prototypes/tf-serving-simple.jsonnet
./examples/prototypes/tf-serving-with-istio.jsonnet
./gcp/prototypes/basic-auth-ingress.jsonnet
./gcp/prototypes/cert-manager.jsonnet
./gcp/prototypes/cloud-endpoints.jsonnet
./gcp/prototypes/google-cloud-filestore-pv.jsonnet
./gcp/prototypes/gpu-driver.jsonnet
./gcp/prototypes/iap-ingress.jsonnet
./gcp/prototypes/metric-collector.jsonnet
./gcp/prototypes/prometheus.jsonnet
./gcp/prototypes/webhook.jsonnet
./jupyter/prototypes/jupyter-web-app.jsonnet
./jupyter/prototypes/jupyter.jsonnet
./jupyter/prototypes/notebook_controller.jsonnet
./jupyter/prototypes/notebooks.jsonnet
./jupyter/sync-notebook.jsonnet
./katib/prototypes/all.jsonnet
./knative-build/prototypes/knative-build.jsonnet
./kubebench/prototypes/kubebench-dashboard.jsonnet
./kubebench/prototypes/kubebench-job.jsonnet
./kubebench/prototypes/kubebench-operator.jsonnet
./metacontroller/prototypes/metacontroller.jsonnet
./modeldb/prototypes/modeldb.jsonnet
./mpi-job/prototypes/mpi-job-custom.jsonnet
./mpi-job/prototypes/mpi-job-simple.jsonnet
./mpi-job/prototypes/mpi-operator.jsonnet
./mxnet-job/prototypes/mxnet-job.jsonnet
./mxnet-job/prototypes/mxnet-operator.jsonnet
./new-package-stub/prototypes/newpackage.jsonnet
./nvidia-inference-server/prototypes/inference-server-all-features.jsonnet
./openvino/prototypes/openvino.jsonnet
./pachyderm/prototypes/pachyderm.jsonnet
./paddle-job/prototypes/paddle-job.jsonnet
./paddle-job/prototypes/paddle-operator.jsonnet
./pipeline/prototypes/pipeline.jsonnet
./profiles/prototypes/profiles.jsonnet
./profiles/sync-permission.jsonnet
./profiles/sync-profile.jsonnet
./pytorch-job/prototypes/pytorch-job.jsonnet
./pytorch-job/prototypes/pytorch-operator.jsonnet
./seldon/prototypes/abtest-v1alpha1.jsonnet
./seldon/prototypes/abtest-v1alpha2.jsonnet
./seldon/prototypes/core.jsonnet
./seldon/prototypes/mab-v1alpha1.jsonnet
./seldon/prototypes/mab-v1alpha2.jsonnet
./seldon/prototypes/outlier-detector-v1alpha1.jsonnet
./seldon/prototypes/outlier-detector-v1alpha2.jsonnet
./seldon/prototypes/serve-simple-v1alpha1.jsonnet
./seldon/prototypes/serve-simple-v1alpha2.jsonnet
./spark/prototypes/spark-job.jsonnet
./spark/prototypes/spark-operator.jsonnet
./tensorboard/prototypes/tensorboard-aws.jsonnet
./tensorboard/prototypes/tensorboard-gcp.jsonnet
./tf-batch-predict/prototypes/tf-batch-predict.jsonnet
./tf-serving/prototypes/tf-serving-all-features.jsonnet
./tf-serving/prototypes/tf-serving-aws.jsonnet
./tf-serving/prototypes/tf-serving-gcp.jsonnet
./tf-serving/prototypes/tf-serving-service.jsonnet
./tf-serving/prototypes/tf-serving-with-request-log.jsonnet
./tf-training/prototypes/tf-job-operator.jsonnet
./weaveflux/prototypes/weaveflux.jsonnet

the list of manifest targets (base|overlay) is 

application/base
argo/base
common/basic-auth/base
common/ambassador/base
common/spartakus/base
common/centraldashboard/base
gcp/iap-ingress/overlays/gcp
gcp/gpu-driver/overlays/gcp
gcp/cert-manager/overlays/gcp
gcp/gcp-credentials-admission-webhook/overlays/gcp
gcp/cloud-endpoints/overlays/gcp
gcp/basic-auth-ingress/overlays/gcp
jupyter/jupyter-web-app/base
jupyter/notebook-controller/base
jupyter/jupyter/overlays/minikube
jupyter/jupyter/base
katib/base
kubebench/base
metacontroller/base
metadata/base
modeldb/base
mutating-webhook/overlays/add-label
mutating-webhook/base
pipeline/pipelines-runner/base
pipeline/api-service/base
pipeline/scheduledworkflow/base
pipeline/minio/base
pipeline/mysql/base
pipeline/pipelines-ui/base
pipeline/pipelines-viewer/base
pipeline/persistent-agent/base
profiles/overlays/devices
profiles/overlays/debug
profiles/base
pytorch-job/pytorch-operator/base
tensorboard/base
tf-training/tf-job-operator/base

it should be possible to determine what's missing

**Comment by jlewi** [comment] 2019-06-26 12:29
Duplicate of #176.

**Closed by jlewi** 2019-06-26 12:29 UTC
