### ISSUE TITLE
Clarify that we must be checked out in a directory called manifests

### ISSUE THREAD

**Issue by holdenk** [kubeflow/manifests#172] opened 2019-06-25 16:32 UTC
If we're checked out in a different directory the generate tests script fail.

**Comment by mattnworb** [comment] 2019-07-19 13:40
This tripped me up as a first-time contributor - and it is made more confusing by the fact that `make generate` in the `tests` directory continues to execute the rest of the make target after `hack/gen-test-targets.sh` errors out:

```
$ pwd
/Users/mattbrown/code/kubeflow-manifests
$ git rev-parse HEAD
63ef9891337a1b44cef88e1815fa0bfee608343c
$ cd tests
$ make generate
must be at manifests root directory to run hack/gen-test-targets.sh
done
go fmt ./...

$ echo $?
0
```

Can I suggest that instead of enforcing that the basename of $PWD has a certain value, to prevent the following lines that assume a certain PWD from erroring out, the script would be more portable to other `git clone` locations/names if you simply let the following commands error out if called from the wrong directory?

https://github.com/kubeflow/manifests/blob/e40fa5359a276c71f8355d74b29f75a1f926b560/hack/gen-test-targets.sh#L8-L13

**Comment by mattnworb** [comment] 2019-07-19 14:38
Alternatively the script could test that `dirname $0` is `hack`.

**Comment by jlewi** [comment] 2019-12-12 07:02
Duplicate of #171

**Closed by jlewi** 2019-12-12 07:02 UTC
