### ISSUE TITLE
fail installing KServe

### ISSUE THREAD

**Issue by hank6086** [kubeflow/manifests#2349] opened 2022-12-21 09:48 UTC
kubernetes version: v1.22.17
kubeflow version: v1.6.1

I tried the installing KServe using the following command
```
kustomize build contrib/kserve/kserve | kubectl apply -f -
```

the log of my installation
```
kubectl logs -n kubeflow -c manager kserve-controller-manager-0
```

```bash=
E1221 09:40:58.550735       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.3/tools/cache/reflector.go:167: Failed to watch *v1beta1.InferenceService: failed to list *v1beta1.InferenceService: Internal error occurred: error resolving resource
E1221 09:41:00.123478       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.3/tools/cache/reflector.go:167: Failed to watch *v1beta1.InferenceService: failed to list *v1beta1.InferenceService: Internal error occurred: error resolving resource
E1221 09:41:02.586315       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.3/tools/cache/reflector.go:167: Failed to watch *v1beta1.InferenceService: failed to list *v1beta1.InferenceService: Internal error occurred: error resolving resource
E1221 09:41:08.739103       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.3/tools/cache/reflector.go:167: Failed to watch *v1beta1.InferenceService: failed to list *v1beta1.InferenceService: Internal error occurred: error resolving resource
E1221 09:41:20.715083       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.3/tools/cache/reflector.go:167: Failed to watch *v1beta1.InferenceService: failed to list *v1beta1.InferenceService: Internal error occurred: error resolving resource
E1221 09:41:44.668393       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.3/tools/cache/reflector.go:167: Failed to watch *v1beta1.InferenceService: failed to list *v1beta1.InferenceService: Internal error occurred: error resolving resource
```

**Comment by traino82** [comment] 2022-12-27 16:56
Similar issue. In my case I've followed the installation guidelines for kserve serverless setup. I'm doing it in a k8s running in minikube. Istio + Knative installed correctly.
`pkg/mod/k8s.io/client-go@v0.19.2/tools/cache/reflector.go:156: Failed to watch *v1beta1.InferenceService: failed to list *v1beta1.InferenceService: Internal error occurred: error resolving resource`

**Comment by RustamGimadiev** [comment] 2022-12-28 08:12
I had solved similar one a month ago, in my case issue was with cert-manager, it was unable to mutate CRD with valid CA certificate (I used AKS so root cause was in enabled admissions)

**Comment by pragadeeshraju** [comment] 2022-12-28 20:14
Similar issue here,

```
│ E1228 20:05:45.338174       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.3/tools/cache/reflector.go:167: Failed to watch *v1beta1.InferenceService: failed to list *v1beta1.InferenceService: Internal error occurred: error resolvi │
│ E1228 20:05:46.398719       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.3/tools/cache/reflector.go:167: Failed to watch *v1beta1.InferenceService: failed to list *v1beta1.InferenceService: Internal error occurred: error resolvi │
│ E1228 20:05:49.338278       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.3/tools/cache/reflector.go:167: Failed to watch *v1beta1.InferenceService: failed to list *v1beta1.InferenceService: Internal error occurred: error resolvi │
│ E1228 20:05:55.073004       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.3/tools/cache/reflector.go:167: Failed to watch *v1beta1.InferenceService: failed to list *v1beta1.InferenceService: Internal error occurred: error resolvi │
│ E1228 20:06:03.447629       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.3/tools/cache/reflector.go:167: Failed to watch *v1beta1.InferenceService: failed to list *v1beta1.InferenceService: Internal error occurred: error resolvi │
│ E1228 20:06:23.730043       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.3/tools/cache/reflector.go:167: Failed to watch *v1beta1.InferenceService: failed to list *v1beta1.InferenceService: Internal error occurred: error resolvi │
│ E1228 20:07:13.089081       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.3/tools/cache/reflector.go:167: Failed to watch *v1beta1.InferenceService: failed to list *v1beta1.InferenceService: Internal error occurred: error resolvi │
│ {"level":"error","ts":1672258065.1406155,"logger":"controller.trainedmodel","msg":"Could not wait for Cache to sync","reconciler group":"serving.kserve.io","reconciler kind":"TrainedModel","error":"failed to wait for trainedmodel cach │
│ {"level":"error","ts":1672258065.1410372,"logger":"controller.inferenceservice","msg":"Could not wait for Cache to sync","reconciler group":"serving.kserve.io","reconciler kind":"InferenceService","error":"failed to wait for inference │
│ {"level":"error","ts":1672258065.141089,"msg":"error received after stop sequence was engaged","error":"failed to wait for inferenceservice caches to sync: timed out waiting for cache to be synced"}                                     │
│ {"level":"info","ts":1672258065.141112,"logger":"controller-runtime.webhook","msg":"shutting down webhook server"}                                                                                                                         │
│ {"level":"error","ts":1672258065.1422656,"logger":"entrypoint","msg":"unable to run the manager","error":"failed to wait for trainedmodel caches to sync: timed out waiting for cache to be synced"}
```
@RustamGimadiev may I know how did you solve it? I use EKS.

**Comment by RustamGimadiev** [comment] 2022-12-28 20:41
In my case, cert-manager was ubanle to update CRD with valid CA due to [admission enforcer](https://learn.microsoft.com/en-us/azure/aks/faq#can-admission-controller-webhooks-impact-kube-system-and-internal-aks-namespaces), it is blocking mutations for system objects
So after creating CRD it continued be with empty caBundle
```
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        caBundle: Cg==
```
So I just added patch with required labels to all mutating webhooks
```
apiVersion: builtin
kind: LabelTransformer
metadata:
  name: commonLabelsTransformer
labels:
  admissions.enforcer/disabled: "true"

fieldSpecs:
- path: metadata/labels
  create: true
  kind: MutatingWebhookConfiguration
- path: metadata/labels
  create: true
  kind: ValidatingWebhookConfiguration
```

It could be useful for AKS, not sure about EKS, never faced something similar on it

Thereby I can imagine that cert-manager injector can not update CRD for some reason, I suggest to check this before deep digging

**Comment by pragadeeshraju** [comment] 2022-12-29 17:52
@RustamGimadiev, thanks for the input. In my case, caBundle is not empty. I should look at the other possibilities.

**Comment by 631068264** [comment] 2023-02-06 08:15
I found that  apply InferenceService get error
```
kubectl apply -f tensor_iris_test.yaml 
Error from server (InternalError): error when retrieving current configuration of:
Resource: "serving.kserve.io/v1beta1, Resource=inferenceservices", GroupVersionKind: "serving.kserve.io/v1beta1, Kind=InferenceService"
Name: "iris-test", Namespace: "default"
from server for: "tensor_iris_test.yaml": Internal error occurred: error resolving resource
```

Get log on  **kserve-controller-manager**

```
E0206 16:08:09.389202       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.3/tools/cache/reflector.go:167: Failed to watch *v1beta1.InferenceService: failed to list *v1beta1.InferenceService: Internal error occurred: error resolving resource
E0206 16:08:10.687503       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.3/tools/cache/reflector.go:167: Failed to watch *v1beta1.InferenceService: failed to list *v1beta1.InferenceService: Internal error occurred: error resolving resource
E0206 16:08:12.636181       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.3/tools/cache/reflector.go:167: Failed to watch *v1beta1.InferenceService: failed to list *v1beta1.InferenceService: Internal error occurred: error resolving resource
E0206 16:08:17.393175       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.3/tools/cache/reflector.go:167: Failed to watch *v1beta1.InferenceService: failed to list *v1beta1.InferenceService: Internal error occurred: error resolving resource
E0206 16:08:25.875289       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.3/tools/cache/reflector.go:167: Failed to watch *v1beta1.InferenceService: failed to list *v1beta1.InferenceService: Internal error occurred: error resolving resource
E0206 16:08:45.947933       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.3/tools/cache/reflector.go:167: Failed to watch *v1beta1.InferenceService: failed to list *v1beta1.InferenceService: Internal error occurred: error resolving resource
E0206 16:09:23.392915       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.3/tools/cache/reflector.go:167: Failed to watch *v1beta1.InferenceService: failed to list *v1beta1.InferenceService: Internal error occurred: error resolving resource
{"level":"error","ts":1675699809.216428,"logger":"controller.inferenceservice","msg":"Could not wait for Cache to sync","reconciler group":"serving.kserve.io","reconciler kind":"InferenceService","error":"failed to wait for inferenceservice caches to sync: timed out waiting for cache to be synced","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:234\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startRunnable.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/manager/internal.go:696"}
{"level":"error","ts":1675699809.216478,"logger":"controller.trainedmodel","msg":"Could not wait for Cache to sync","reconciler group":"serving.kserve.io","reconciler kind":"TrainedModel","error":"failed to wait for trainedmodel caches to sync: timed out waiting for cache to be synced","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:234\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startRunnable.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/manager/internal.go:696"}
{"level":"info","ts":1675699809.2167053,"logger":"controller-runtime.webhook","msg":"shutting down webhook server"}
{"level":"error","ts":1675699809.216767,"msg":"error received after stop sequence was engaged","error":"failed to wait for trainedmodel caches to sync: timed out waiting for cache to be synced"}
{"level":"error","ts":1675699809.2180226,"logger":"entrypoint","msg":"unable to run the manager","error":"failed to wait for inferenceservice caches to sync: timed out waiting for cache to be synced"}
```

**Comment by wang-mask** [comment] 2023-03-23 09:08
i met the same problem

**Comment by wang-mask** [comment] 2023-03-23 11:57
> I found that apply InferenceService get error in kubernetes version: rke k8s 1.23.16 kubeflow version: v1.6.1
> 
> ```
> kubectl apply -f tensor_iris_test.yaml 
> Error from server (InternalError): error when retrieving current configuration of:
> Resource: "serving.kserve.io/v1beta1, Resource=inferenceservices", GroupVersionKind: "serving.kserve.io/v1beta1, Kind=InferenceService"
> Name: "iris-test", Namespace: "default"
> from server for: "tensor_iris_test.yaml": Internal error occurred: error resolving resource
> ```
> 
> Get log on **kserve-controller-manager**
> 
> ```
> E0206 16:08:09.389202       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.3/tools/cache/reflector.go:167: Failed to watch *v1beta1.InferenceService: failed to list *v1beta1.InferenceService: Internal error occurred: error resolving resource
> E0206 16:08:10.687503       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.3/tools/cache/reflector.go:167: Failed to watch *v1beta1.InferenceService: failed to list *v1beta1.InferenceService: Internal error occurred: error resolving resource
> E0206 16:08:12.636181       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.3/tools/cache/reflector.go:167: Failed to watch *v1beta1.InferenceService: failed to list *v1beta1.InferenceService: Internal error occurred: error resolving resource
> E0206 16:08:17.393175       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.3/tools/cache/reflector.go:167: Failed to watch *v1beta1.InferenceService: failed to list *v1beta1.InferenceService: Internal error occurred: error resolving resource
> E0206 16:08:25.875289       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.3/tools/cache/reflector.go:167: Failed to watch *v1beta1.InferenceService: failed to list *v1beta1.InferenceService: Internal error occurred: error resolving resource
> E0206 16:08:45.947933       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.3/tools/cache/reflector.go:167: Failed to watch *v1beta1.InferenceService: failed to list *v1beta1.InferenceService: Internal error occurred: error resolving resource
> E0206 16:09:23.392915       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.22.3/tools/cache/reflector.go:167: Failed to watch *v1beta1.InferenceService: failed to list *v1beta1.InferenceService: Internal error occurred: error resolving resource
> {"level":"error","ts":1675699809.216428,"logger":"controller.inferenceservice","msg":"Could not wait for Cache to sync","reconciler group":"serving.kserve.io","reconciler kind":"InferenceService","error":"failed to wait for inferenceservice caches to sync: timed out waiting for cache to be synced","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:234\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startRunnable.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/manager/internal.go:696"}
> {"level":"error","ts":1675699809.216478,"logger":"controller.trainedmodel","msg":"Could not wait for Cache to sync","reconciler group":"serving.kserve.io","reconciler kind":"TrainedModel","error":"failed to wait for trainedmodel caches to sync: timed out waiting for cache to be synced","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/internal/controller/controller.go:234\nsigs.k8s.io/controller-runtime/pkg/manager.(*controllerManager).startRunnable.func1\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.2/pkg/manager/internal.go:696"}
> {"level":"info","ts":1675699809.2167053,"logger":"controller-runtime.webhook","msg":"shutting down webhook server"}
> {"level":"error","ts":1675699809.216767,"msg":"error received after stop sequence was engaged","error":"failed to wait for trainedmodel caches to sync: timed out waiting for cache to be synced"}
> {"level":"error","ts":1675699809.2180226,"logger":"entrypoint","msg":"unable to run the manager","error":"failed to wait for inferenceservice caches to sync: timed out waiting for cache to be synced"}
> ```

how do you solve this problem?

**Comment by punkerpunker** [comment] 2023-04-01 19:04
I had the same issue when I was upgrading from KServe v0.7 to v0.10. For me, the following steps helped: 

1. Restart the cert-manager
2. I was having an `ignoreDifferences` entry in my ArgoCD definition for KServe webhooks:
```
ignoreDifferences:
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
    jsonPointers:
      - /rules
  - group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    jsonPointers:
      - /spec/conversion/webhook/clientConfig/caBundle
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
      - '.webhooks[]?.clientConfig.caBundle'
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jqPathExpressions:
      - '.webhooks[]?.clientConfig.caBundle'
```

So, those were not recreated with the rolling update. Refreshing caBundle by recreating them manually actually solved the issue for me.

**Comment by jatin-jangir-0220** [comment] 2023-07-07 14:17
Is there any solution in case of EKS ?

**Comment by shiveshabhishek** [comment] 2023-07-24 10:02
For me, it was due to the kserve inferenceservice CRD in k8s v1.26.6
It was using a weird caBundle present in that CRD...

So, due to that we were getting error in our apiserver as
```
E0719 12:04:39.813292       1 customresource_handler.go:304] unable to load root certificates: unable to parse bytes as PEM block
```

Once I patched it to remove it's finalizers,it deleted all the namespaces stuck in Terminating state.

`kubectl patch crd/inferenceservices.serving.kserve.io -p '{"metadata":{"finalizers":[]}}' --type=merge`

The culprit >>
```
templates/kserve.yaml:748:    caBundle: Cg==
```

**Comment by juliusvonkohout** [comment] 2023-11-29 16:54
/close

we are at Kubeflow 1.8 now

**Closed by juliusvonkohout** 2023-11-29 16:54 UTC
