### ISSUE TITLE
Upgrade process

### ISSUE THREAD

**Issue by N214** [kubeflow/manifests#2495] opened 2023-07-29 03:29 UTC
Hi,

I am successfully installed kubeflow, but I'm wondering how kubeflow or the different parts should be upgraded in the future?

And how should the upgrade process be? I did not find any documentation for that. 

Thank you

**Comment by juliusvonkohout** [comment] 2023-08-25 09:47
/close 

duplicate of #2216

**Closed by juliusvonkohout** 2023-08-25 09:47 UTC

**Comment by juliusvonkohout** [comment] 2024-05-16 14:11
Solved by https://github.com/kubeflow/manifests/pull/2717
