### ISSUE TITLE
kfdef on v1.0 branch broken

### ISSUE THREAD

**Issue by kunmingg** [kubeflow/manifests#1036] opened 2020-03-20 21:03 UTC
`kfctl build https://github.com/kubeflow/manifests/blob/v1.0-branch/kfdef/kfctl_gcp_iap.v1.0.0.yaml`

throws error 

`"failed to build kfApp from URI: couldn't generate KfApp:  (kubeflow.error): Code 500 with message: kfApp Generate failed for kustomize: kustomize generate failed Error:  (kubeflow.error): Code 500 with message: couldn't copy application kfserving-gateway","time":"2020-03-20T20:49:29Z"}`

**Comment by jlewi** [comment] 2020-03-24 04:01
@kunmingg Can we close this? Is it fixed by #1037?

**Comment by jlewi** [comment] 2020-04-06 14:35
Duplicate of #1029

**Closed by jlewi** 2020-04-06 14:35 UTC
Labels: area/kfctl, kind/bug, priority/p0
