### ISSUE TITLE
Using keycloak as external OIDC provider on kubeflow (instead of dex)

### ISSUE THREAD

**Issue by zibuyule** [kubeflow/manifests#2513] opened 2023-08-22 13:01 UTC
kubeflow version: v1.7.0

My keycloak server is "http://10.86.26.178:8081".
Before using keycloak, I can access my kubeflow page through "http://10.86.26.241".

$ cd kubeflow/manifests/common/oidc-authservice/base
$ cat params.env
```
OIDC_PROVIDER=http://10.86.26.178:8081/realms/kubeflow
OIDC_AUTH_URL=http://10.86.26.178:8081/realms/kubeflow/protocol/openid-connect/auth
OIDC_SCOPES=profile email
SKIP_AUTH_URI=/realms

AUTHSERVICE_URL_PREFIX=/authservice/

REDIRECT_URL=http://10.86.26.241/login/oidc

USERID_HEADER=kubeflow-userid
USERID_PREFIX=
USERID_CLAIM=email
PORT="8080"
STORE_PATH=/var/lib/authservice/data.db
```

$ cat secret_params.env
```
CLIENT_ID=kubeflow
CLIENT_SECRET=7HRNuyvjeAlXAWuxAKunVROeisxxxxx
```

$ kustomize build common/oidc-authservice/base |kubectl delete -f -
$ kustomize build common/oidc-authservice/base |kubectl apply  -f -

```
When I visit http://http://10.86.26.241 through the browser, the page is redirected to the keycloak page 
and is asked to enter the username and password. Once I enter the username and password created
 in the realm of kubeflow in keycloak, I will get a display "too many redirects".

The keycloak realms kubelow set the  valid redirect uris "http://10.86.26.241/login/oidc" or 
"http://10.86.26.241/login/oidc/*" or "http://10.86.26.241/*", still all getting the above error page.
```

**Comment by juliusvonkohout** [comment] 2023-08-25 09:44
/close

duplicate of #2379

**Closed by juliusvonkohout** 2023-08-25 09:44 UTC
