### ISSUE TITLE
metadata deployment on master is broken; missing secret metadata-db-secrets

### ISSUE THREAD

**Issue by jlewi** [kubeflow/manifests#799] opened 2020-01-29 13:11 UTC
On master (and likely 1.0). 

The metadata deployment is broken. A lot of containers can't start because the secret `metadata-db-secrets` is missing.

Attached is the output of kubectl describe for one such pod.

[metadata-deployment-54ff5d695d-j949l.txt](https://github.com/kubeflow/manifests/files/4128115/metadata-deployment-54ff5d695d-j949l.txt)

/assign @zhenghuiwang

**Comment by zhenghuiwang** [comment] 2020-01-29 23:42
After reproducing this issue, I tried to manually kustomize apply the `db` overlay. Then the secret was created. 

I guess there is a bug in the kfctl apply logic of merging/applying the overlays and found this issue and a pending fix:
https://github.com/kubeflow/kfctl/issues/156
https://github.com/kubeflow/kfctl/pull/187

**Comment by zhenghuiwang** [comment] 2020-01-30 21:21
Verified this issue is fixed by kubeflow/kfctl#156

**Comment by jlewi** [comment] 2020-02-03 18:50
@zhenghuiwang Has this been cherry picked into a kfctl RC yet?

**Comment by zhenghuiwang** [comment] 2020-02-03 18:57
https://github.com/kubeflow/kfctl/pull/204 is the cherry-pick but not merged due to the tests failed.

**Comment by zhenghuiwang** [comment] 2020-02-04 21:10
The fix was cherry-picked in kfctl `v1.0-rc3` release:
https://github.com/kubeflow/kfctl/commit/cba38248608412141110ddf53ef9c18e173195d0

**Closed by zhenghuiwang** 2020-02-04 21:10 UTC
Labels: area/metadata, kind/bug, priority/p0

**Comment by jlewi** [comment] 2020-02-05 00:20
Here's a list of pod confirming they all come up

[pods.txt](https://github.com/kubeflow/manifests/files/4156810/pods.txt)

This was deployed with
https://github.com/kubeflow/manifests/tree/32aba35
kfctl:  kfctl-v1-0-rc-2-13-g521fcfe
