### ISSUE TITLE
making post requests to inferenceService, but logs show GET  request received with 404

### ISSUE THREAD

**Issue by khalidkhushal** [kubeflow/manifests#2688] opened 2024-04-22 13:45 UTC
Hi,

I am trying to deploy kserve using kubeflow raw manifest on K3s cluster.
I can create a inferenceService and is shown as READY as stated below:

`NAMESPACE                   NAME             URL                                                                      READY   PREV   LATEST   PREVROLLEDOUTREVISION   LATESTREADYREVISION              AGE
kubeflow-user-example-com   sklearn-iris-2   http://sklearn-iris-2.kubeflow-user-example-com.192.168.10.49.sslip.io   True           100                              sklearn-iris-2-predictor-00001   100m
kubeflow-user-example-com   sklearn-iris     http://sklearn-iris.kubeflow-user-example-com.192.168.10.49.sslip.io     True           100                              sklearn-iris-predictor-00001     20m`

I am making request on this using jupyter notebook, created from kubeflow in same namespace, with following code:

===========
`url= "http://sklearn-iris.kubeflow-user-example-com.192.168.10.49.sslip.io"

body = json.dumps({
  'instances': [
    [6.8,  2.8,  4.8,  1.4],
    [6.0,  3.4,  4.5,  1.6]
  ]
})

headers = {'Content-Type': 'application/json'}

print("URL ==========>", url)
response = requests.post(url, headers=headers, data=body, verify=False)

print("response=====>",response.json())`

========
But in logs it shows GET request with 404 error:

`2024-04-22 13:05:38.559 uvicorn.error INFO:     Started server process [1] 
 2024-04-22 13:05:38.560 uvicorn.error INFO:     Waiting for application startup. 
 2024-04-22 13:05:38.563 1 kserve INFO [start():62] Starting gRPC server on [::]:8081 
 2024-04-22 13:05:38.563 uvicorn.error INFO:     Application startup complete. 
 2024-04-22 13:05:38.563 uvicorn.error INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit) 
 2024-04-22 13:13:18.987 uvicorn.access INFO:     10.42.0.216:0 1 - "GET /dex/auth?client_id=kubeflow-oidc-authservice&redirect_uri=%2Fauthservice%2Foidc%2Fcallback&response_type=code&scope=openid+profile+email+groups&state=MTcxMzc5MTU5OHxOd3dBTkVoTVZqTk5NMUJPU0ZoVlVUSkRRVE5RUTFKUVNsbFJWVU5RUlZCUFJEWkdTbGRDVkU0eVJGUTNTa1JRV1RSVVdrOHlNbEU9fG6TTEoiRo50s6nAwZRUnEiQBr2KSckfvQBTkZZD-sT5 HTTP/1.1" 404 Not Found 
 2024-04-22 13:13:18.987 kserve.trace kserve.io.dex.auth: 0.0005548000335693359 
 2024-04-22 13:13:18.987 kserve.trace kserve.io.dex.auth: 0.0005500000000004945`
 
 
What could possibly  the reason to it?
I have bee debugging this but had no luck.

Thanks in advance.

**Comment by juliusvonkohout** [comment] 2024-05-07 09:08
Feel free to join our slack channel wg-manifests here https://www.kubeflow.org/docs/about/community/ , it also contains our meeting schedule.

**Comment by khalidkhushal** [comment] 2024-05-09 06:24
Thanks for the response!

How can I authenticate my request, within the same namespace?
I am making request from jupyter notebook created on kubeflow.

**Comment by juliusvonkohout** [comment] 2024-06-21 09:37
CC @kromanow94

**Comment by kromanow94** [comment] 2024-06-21 09:52
There is definitely a way. I don't have too much time today to get more into details but I should be able to help. If you can create replication steps, that would be great. I know these are not too complicated but still would help to define the exact scenario and acceptance criteria.

**Comment by juliusvonkohout** [comment] 2024-07-22 17:46
Probably a duplicate of https://github.com/kubeflow/manifests/issues/2575

**Closed by juliusvonkohout** 2024-07-22 17:46 UTC

**Comment by juliusvonkohout** [comment] 2024-07-22 17:51
Lets continue with secure stuff in https://github.com/kubeflow/manifests/issues/2811
