### ISSUE TITLE
Auto PR doesn't change image tag under tests/stack/gcp

### ISSUE THREAD

**Issue by Jeffwan** [kubeflow/manifests#1298] opened 2020-06-22 17:35 UTC
Meet a problem in #1293 

```
--- a/tests/stacks/gcp/test_data/expected/apps_v1_deployment_tf-job-operator.yaml
+++ b/tests/stacks/gcp/test_data/expected/apps_v1_deployment_tf-job-operator.yaml
@@ -38,6 +38,6 @@ spec:
           valueFrom:
             fieldRef:
               fieldPath: metadata.name
-        image: gcr.io/kubeflow-images-public/tf_operator:vmaster-gd455e6ef
+        image: gcr.io/kubeflow-images-public/tf_operator:vmaster-ga2ae7bff
         name: tf-job-operator
       serviceAccountName: tf-job-operator
(END)
```

I notice #1270 doesn't update this file `tests/stacks/gcp/test_data/expected/apps_v1_deployment_tf-job-operator.yaml` and my local test failed. 

A change a needed to cover `stacks/gcp`

**Comment by jlewi** [comment] 2020-06-22 20:21
@Jeffwan and @andreyvelich this is WAI

#1270 was opened five days ago. The GCP stack was added after that PR was merged in #1286. This explains why when #1270 ran the GCP stack wasn't updated.

**Closed by jlewi** 2020-06-22 20:21 UTC
Labels: area/testing, kind/bug, priority/p1

**Comment by andreyvelich** [comment] 2020-06-22 20:28
@jlewi Thank you, I think you are right.
Can we somehow synchronised the Auto PRs with the current upstream tests?
For example, make sure that Auto PRs is rebasing on the latest upstream commit?

This can help to avoid situation when Auto PR tests is not sync with current upstream branch.

**Comment by jlewi** [comment] 2020-06-23 00:20
@andreyvelich This is not an issue with auto PRs. The issue is more general. When the PR was created it was based off the latest commit on master; the same as for a manual PR. Over the course of the lifetime of the PR, changes are merged to master; these won't be on the PR branch unless the user rebases on master. 

If we force PRs to be in sync with master then after every PR is merged all open PRs need to be rebased.

**Comment by jlewi** [comment] 2020-06-23 01:10
I think this was a weird edge case which should only happen rarely.

The GCP stack was added in #1270; but due to a bug the tests weren't being generated until #1288

**Comment by andreyvelich** [comment] 2020-06-23 01:31
> I think this was a weird edge case which should only happen rarely.
> 
> The GCP stack was added in #1270; but due to a bug the tests weren't being generated until #1288

I am wondering how we can control that cases. And is it a good strategy to create PR to fix unit tests. 
For example, if PR was created few days ago and passed the tests, it is not 100% that unit tests will be passed today.

The same situation happened here: https://github.com/kubeflow/manifests/pull/1255. After https://github.com/kubeflow/manifests/pull/1249 got merged, I didn't rerun tests for https://github.com/kubeflow/manifests/pull/1239 and test was broken.

If it is possible, maybe we could run presubmit-test after PR gets appropriate labels for merging.
