### ISSUE TITLE
Add a way to set networkRef and subnetworkRef to ContainerCluster (cnrm)

### ISSUE THREAD

**Issue by kelvins** [kubeflow/manifests#1578] opened 2020-10-08 15:14 UTC
Similar to the issue https://github.com/kubeflow/manifests/issues/1577, it would be great to add a way to set `networkRef` and `subnetworkRef` properties to the `ContainerCluster` manifest (cnrm):

https://github.com/kubeflow/manifests/blob/c728bc737cfadc2816ecd50c5c96ee59cd1d9b1a/gcp/v2/cnrm/cluster/cluster.yaml#L17-L62

Since `networkRef` and` subnetworkRef` have multiple properties (`external`, `name` and` namespace`), I'm not sure if this can be done using` kpt`. Anyway, if it is not possible to define using `kpt`, it would be good to include at least a manual way of doing this in the documentation.

**Comment by jlewi** [comment] 2020-10-19 13:28
Can you use kustomize and an overlay?

**Comment by jlewi** [comment] 2020-10-19 13:30
Duplicate of #1577

**Closed by jlewi** 2020-10-19 13:30 UTC
Labels: kind/feature, platform/gcp, priority/p2
